dataset_paths:
  rwrf: "/workspace/NCDR_StormCast/data/RWRF"
  era5: "/workspace/NCDR_StormCast/era5"
  qpepre: "../data/pptn"
  era5_npz: "/workspace/NCDR_StormCast/era5_npz/"
  rwrf_npz: "/workspace/NCDR_StormCast/rwrf_npz/"


# dates for dataset
date_strs: ["2019/08/03"]
hr_strs: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09",
         "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
         "21", "22", "23"]
