dataset_paths:
  rwrf: "/workspace/dev/data/rwrf"
  era5: "/workspace/dev/data/era5/train"
  qpepre: "/workspace/dev/data/pptn"

# dates for dataset
date_strs: ["2019/08/03"]
hr_strs: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09",
         "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20",
         "21", "22", "23"]
