data:
  conditioning_dt: 1
  local_img_size: [512, 640]
  n_local_channels: 99
  n_conditioning_channels: 26
  n_invariant: 2
  invariants: ["lsm", "orog"]

  local_channels: ['u10m', 'v10m', 't2m', 'mslp', 'u1hl', 'u2hl', 'u3hl', 'u4hl', 'u5hl', 'u6hl', 'u7hl', 'u8hl', 'u9hl', 'u10hl', 'u11hl', 'u13hl', 'u15hl', 'u20hl', 'u25hl', 'u30hl', 'v1hl', 'v2hl', 'v3hl', 'v4hl', 'v5hl', 'v6hl', 'v7hl', 'v8hl', 'v9hl', 'v10hl', 'v11hl', 'v13hl', 'v15hl', 'v20hl', 'v25hl', 'v30hl', 't1hl', 't2hl', 't3hl', 't4hl', 't5hl', 't6hl', 't7hl', 't8hl', 't9hl', 't10hl', 't11hl', 't13hl', 't15hl', 't20hl', 't25hl', 't30hl', 'q1hl', 'q2hl', 'q3hl', 'q4hl', 'q5hl', 'q6hl', 'q7hl', 'q8hl', 'q9hl', 'q10hl', 'q11hl', 'q13hl', 'q15hl', 'q20hl', 'q25hl', 'q30hl', 'Z1hl', 'Z2hl', 'Z3hl', 'Z4hl', 'Z5hl', 'Z6hl', 'Z7hl', 'Z8hl', 'Z9hl', 'Z10hl', 'Z11hl', 'Z13hl', 'Z15hl', 'Z20hl', 'Z25hl', 'Z30hl', 'p1hl', 'p2hl', 'p3hl', 'p4hl', 'p5hl', 'p6hl', 'p7hl', 'p8hl', 'p9hl', 'p10hl', 'p11hl', 'p13hl', 'p15hl', 'p20hl', 'refc']
  conditioning_channels: ['u10m', 'v10m', 't2m', 'tcwv', 'msl', 'sp', 'u1000', 'u850', 'u500', 'u250', 'v1000', 'v850', 'v500', 'v250', 'z1000', 'z850', 'z500', 'z250', 't1000', 't850', 't500', 't250', 'q1000', 'q850', 'q500', 'q250']

regression_model:
  _target_: earth2studio.models.nn.stormcast_networks.RegressionWrapperV2
  model:
    _target_: earth2studio.models.nn.stormcast_networks.SongUNetRegression
    img_resolution: 512
    in_channels: ${eval:'${data.n_local_channels}+${data.n_conditioning_channels}+${data.n_invariant}'}
    out_channels: ${data.n_local_channels}
    label_dim: 0
    embedding_type: "zero"
    encoder_type: "standard"
    decoder_type: "standard"
    channel_mult_noise: 1
    resample_filter: [1, 1]
    model_channels: 128
    channel_mult: [1, 2, 2, 2, 2]
    attn_resolutions: []
    spatial_embedding: False
    hrrr_resolution: [512, 640]
  img_resolution: 512
  label_dim: 0

diffusion_model:
  _target_: earth2studio.models.nn.stormcast_networks.EDMPrecond
  model: 
    _target_: earth2studio.models.nn.stormcast_networks.SongUNet
    img_resolution: 512
    in_channels: ${eval:'3 * ${data.n_local_channels} + ${data.n_invariant}'}
    out_channels: ${data.n_local_channels}
    label_dim: 0
    embedding_type: "positional"
    encoder_type: "standard"
    decoder_type: "standard"
    channel_mult_noise: 1
    resample_filter: [1, 1]
    model_channels: 128
    channel_mult: [1, 2, 2, 2, 2]
    attn_resolutions: []
    spatial_embedding: True
    hrrr_resolution: [512, 640]
  img_resolution: 512
  label_dim: 0

sampler_args: